version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200mk
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: echo 'export GRADLE_OPTS="-Dfile.encoding=UTF-8"' >> $BASH_ENV
      - run: rm -rf build/libs
      - run: chmod +x ./gradlew
      - run: sed -i "s/BUILD_ID/${CIRCLE_BUILD_NUM}/g" build.gradle
      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: build/libs
          destination: jars